using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using XPacketRpc.Generators.Diagnostics;
using XPacketRpc.Generators.Discovery;
using XPacketRpc.Generators.Emit;

namespace XPacketRpc.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class XPacketRpcGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            const string marker = """
                // <auto-generated/>
                namespace XPacketRpc.Generated;
                internal static class __GeneratorMarker { public const string Version = "0.1"; }
                """;
            ctx.AddSource("__GeneratorMarker.g.cs", SourceText.From(marker, Encoding.UTF8));
        });

        var callSites = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is InvocationExpressionSyntax,
                transform: static (ctx, ct) =>
                {
                    var inv = (InvocationExpressionSyntax)ctx.Node;
                    return (inv, ctx.SemanticModel);
                })
            .Collect();

        var compilationAndCallSites = context.CompilationProvider.Combine(callSites);

        context.RegisterSourceOutput(compilationAndCallSites, static (spc, pair) =>
        {
            var (compilation, sites) = pair;
            Execute(spc, compilation, sites);
        });
    }

    private static void Execute(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<(InvocationExpressionSyntax inv, SemanticModel model)> sites)
    {
        var walker = new TypeWalker(compilation);
        var discovered = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);

        foreach (var (inv, model) in sites)
        {
            var symbol = model.GetSymbolInfo(inv).Symbol as IMethodSymbol;
            if (symbol is null) continue;
            if (symbol.TypeArguments.Length != 1) continue;

            var container = symbol.ContainingType;
            if (container is null) continue;
            var fq = container.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            bool isXPRpc = fq == "global::XPacketRpc.XPRpc" &&
                           (symbol.Name == "Touch" || symbol.Name == "Write" || symbol.Name == "Read");
            bool isSerializer = (fq == "global::XPacketRpc.IRpcSerializer" ||
                                 container.AllInterfaces.Any(i =>
                                     i.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) ==
                                     "global::XPacketRpc.IRpcSerializer"))
                && (symbol.Name == "Serialize" || symbol.Name == "Deserialize");
            if (!isXPRpc && !isSerializer) continue;

            var t = symbol.TypeArguments[0];
            if (t.TypeKind == TypeKind.TypeParameter)
            {
                spc.ReportDiagnostic(Diagnostic.Create(
                    Descriptors.OpenGenericCallSite,
                    inv.GetLocation(),
                    symbol.Name, t.Name));
                continue;
            }

            if (t is INamedTypeSymbol nts) discovered.Add(nts);
        }

        var allTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
        foreach (var d in discovered)
        {
            foreach (var t in walker.Closure(d))
            {
                allTypes.Add(t);
            }
        }

        var writeEmitter = new WriteEmitter(walker);
        var readEmitter = new ReadEmitter(walker);
        var emittedTypes = new List<INamedTypeSymbol>();

        foreach (var t in allTypes)
        {
            if (IsBuiltinSkipType(t)) continue;

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("namespace XPacketRpc.Generated;");
            sb.AppendLine();
            sb.AppendLine($"internal static class __XPRpcGen_{Sanitize(t.Name)}");
            sb.AppendLine("{");
            sb.AppendLine(writeEmitter.EmitWriteMethod(t));
            sb.AppendLine();
            sb.AppendLine(readEmitter.EmitReadMethod(t));
            sb.AppendLine("}");

            spc.AddSource($"__XPRpcGen_{Sanitize(t.Name)}.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8));
            emittedTypes.Add(t);
        }

        if (emittedTypes.Count > 0)
        {
            var reg = new RegistryEmitter().Emit(
                emittedTypes,
                compilation.AssemblyName ?? "Unknown");
            spc.AddSource("__XPRpcRegistry.g.cs", SourceText.From(reg, Encoding.UTF8));
        }
    }

    private static bool IsBuiltinSkipType(INamedTypeSymbol t)
    {
        var ns = t.ContainingNamespace?.ToDisplayString();
        if (ns == "System" || (ns != null && ns.StartsWith("System.")))
            return true;

        // Skip types that are not publicly accessible (e.g. private nested types in test classes).
        ISymbol current = t;
        while (current is not null)
        {
            if (current.DeclaredAccessibility == Accessibility.Private ||
                current.DeclaredAccessibility == Accessibility.Protected ||
                current.DeclaredAccessibility == Accessibility.ProtectedAndInternal)
                return true;
            current = current.ContainingSymbol;
            if (current is INamespaceSymbol) break;
        }
        return false;
    }

    private static string Sanitize(string s)
    {
        var chars = new char[s.Length];
        for (int i = 0; i < s.Length; i++)
            chars[i] = char.IsLetterOrDigit(s[i]) ? s[i] : '_';
        return new string(chars);
    }
}
