using System.Collections.Generic;
using Microsoft.CodeAnalysis;

namespace XPacketRpc.Generators.Emit;

internal sealed class RegistryEmitter
{
    public string Emit(IEnumerable<INamedTypeSymbol> types, string assemblyName)
    {
        var nsSafe = SanitizeNamespace(assemblyName);
        var sb = new IndentedStringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace XPacketRpc.Generated.{nsSafe};");
        sb.AppendLine();
        sb.AppendLine("internal static class __XPRpcRegistry");
        sb.AppendLine("{");
        using (sb.Indent())
        {
            sb.AppendLine("[global::System.Runtime.CompilerServices.ModuleInitializer]");
            sb.AppendLine("internal static void Init()");
            sb.AppendLine("{");
            using (sb.Indent())
            {
                foreach (var t in types)
                {
                    var fq = "global::" + t.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", "");
                    var sname = Sanitize(t.Name);
                    sb.AppendLine($"global::XPacketRpc.XPRpc.Register<{fq}>(__XPRpcGen_{sname}.Write, __XPRpcGen_{sname}.Read);");
                }
            }
            sb.AppendLine("}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string SanitizeNamespace(string s)
    {
        var chars = new char[s.Length];
        for (int i = 0; i < s.Length; i++)
        {
            char c = s[i];
            chars[i] = (char.IsLetterOrDigit(c) || c == '_' || c == '.') ? c : '_';
        }
        if (chars.Length > 0 && char.IsDigit(chars[0])) return "_" + new string(chars);
        return new string(chars);
    }

    private static string Sanitize(string s)
    {
        var chars = new char[s.Length];
        for (int i = 0; i < s.Length; i++)
            chars[i] = char.IsLetterOrDigit(s[i]) ? s[i] : '_';
        return new string(chars);
    }
}
